### ISSUE TITLE
在leaves启用RNG钓鱼时为clientcommand启用/cfish命令

### ISSUE THREAD

**Issue by Error-106** [LeavesMC/Bladeren#2]

**Comment by LittleChest** [comment]
猜到了 我在clientcommand看到了一行注释 1.20+不启用
应该询问@Earthcomputer

**Comment by Error-106** [comment]
> 猜到了 我在clientcommand看到了一行注释 1.20+不启用
> 应该询问@Earthcomputer

这个功能是给LeavesMC/Leaves #120准备的

**Comment by Error-106** [comment]
Earthcomputer在clientcommands的#534中提到了原因

**Comment by LittleChest** [comment]
前几天测试了一下 已经有了 把问题关掉吧）
